### ISSUE TITLE
can be deploy on public cpaas like heroku or dockerised it ?

### ISSUE THREAD

**Issue by todokku** [mdundek/mycloud#3]
Hi Michael,
can be deploy on public cpaas like heroku or dockerised it ?
if its possible please add deploy to heroku button or dockerfile on root
waiting for your response 
finest regards

**Comment by mdundek** [comment]
Hello todokku,

Thanks for the interest, I am still cleaning up some things in the code to stabilize the core components, hopefully by the middle of next week I will be done with that. The installation script will also be updated by then, I found some inconsistencies in the current documentation when it comes to installing MyCloud. That documentation is in the middle of being constructed, and is far from complete anyway.
That said, MyCLoud PaaS is designed to be a PaaS platform on it's own. For example, RedHat Openshift is designed to run as one K8S cluster, MyCloud is lower-level than that (even if MyCloud has some of the features of OpenShift such as service provisioning or application deployments just to name a few), it is designed to be a multi-tenant private cloud platform that can spin up and scale multiple clusters for different tenants. Installing it on something like Heroku is not possible, you need VM's or physical machines to install MyCloud. Even though running docker containers inside docker containers is possible, it is not a viable approach to build a production environment with multi tenancy and the need for strong tennant decoupling. You could install MyCloud on AWS EC2 or Azure VMs..., but not on another Kubernetes or CloudFoundry instance. Later on, if the platform grows and becomes more mature, it might be interesting to add support for single tenancy  by installing it on an existing cluster, but that's not a short term goal. If that's what you are looking for, have a look at OKD (https://www.okd.io/), it's the open source version of Openshift.
Hope that makes things more clear.
Best regards
